// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ0k3uYG-3wefqZqjH9GnLDYU-ChhMSAM',
    appId: '1:1058526483012:web:fd7e1aea640cd2464e6211',
    messagingSenderId: '1058526483012',
    projectId: 'ocrsjfltr',
    authDomain: 'ocrsjfltr.firebaseapp.com',
    storageBucket: 'ocrsjfltr.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDzWnUDnrY57nt4H7jBFd8ATDr-9b9Y-Q',
    appId: '1:1058526483012:android:92d3935bd53ed5de4e6211',
    messagingSenderId: '1058526483012',
    projectId: 'ocrsjfltr',
    storageBucket: 'ocrsjfltr.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCII3STP3P5LPrtxUDiWLqUWWUluWATbec',
    appId: '1:1058526483012:ios:69080ee453c42f2a4e6211',
    messagingSenderId: '1058526483012',
    projectId: 'ocrsjfltr',
    storageBucket: 'ocrsjfltr.firebasestorage.app',
    iosBundleId: 'com.example.concreteCubeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCII3STP3P5LPrtxUDiWLqUWWUluWATbec',
    appId: '1:1058526483012:ios:69080ee453c42f2a4e6211',
    messagingSenderId: '1058526483012',
    projectId: 'ocrsjfltr',
    storageBucket: 'ocrsjfltr.firebasestorage.app',
    iosBundleId: 'com.example.concreteCubeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJ0k3uYG-3wefqZqjH9GnLDYU-ChhMSAM',
    appId: '1:1058526483012:web:fba35c1a6ef68fc54e6211',
    messagingSenderId: '1058526483012',
    projectId: 'ocrsjfltr',
    authDomain: 'ocrsjfltr.firebaseapp.com',
    storageBucket: 'ocrsjfltr.firebasestorage.app',
  );

}